config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/fair-workflows/fairworkflows:
      branch: main
      repo: https://github.com/fair-workflows/fairworkflows
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/fair-workflows/fairworkflows git:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-smalt-dormouse.sh
        container: qc.acc_cloudy-wheat-gorilla
  QC.Doc:
    repos:
      github.com/fair-workflows/fairworkflows find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-peach-dingo.sh
        container: qc.doc_geeky-pumpkin-dragonfly
      github.com/fair-workflows/fairworkflows git:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-violet-horse.sh
        container: qc.doc_lousy-red-chow
      github.com/fair-workflows/fairworkflows markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-copper-owl.sh
        container: qc.doc_sleazy-firebrick-capybara
      github.com/fair-workflows/fairworkflows restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-grey-mastiff.sh
        container: qc.doc_gloppy-tangerine-wolfhound
  QC.Lic:
    repos:
      github.com/fair-workflows/fairworkflows licensee:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-malachite-fowl.sh
        container: qc.lic_thirsty-cardinal-lemming
  QC.Met:
    repos:
      github.com/fair-workflows/fairworkflows cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-myrtle-balinese.sh
        container: qc.met_hilly-dandelion-argentino
  QC.Sec:
    repos:
      github.com/fair-workflows/fairworkflows bandit:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-rust-rottweiler.sh
        container: qc.sec_clammy-teal-binturong
  QC.Sty:
    repos:
      github.com/fair-workflows/fairworkflows flake8:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-salmon-whale.sh
        container: qc.sty_crabby-maroon-bloodhound
  QC.Ver:
    repos:
      github.com/fair-workflows/fairworkflows get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-persimmon-tarantula.sh
        container: qc.ver_skinny-razzmatazz-raccoon
timeout: 5400
